### PR TITLE
`YamlRenderer`: allow all primitive scalar types as map keys

### LINKED ISSUE #878: Not possible to render mapping with Int keys in YAML
```
ll = new Mapping<Int, String>{
  [1] = ""
}
```

when trying to render it, I get an error:

```
–– Pkl Error ––
Cannot render object with non-string key as XML.
Object: new Mapping { [1] = "" }
Key   : 1
```

### PR DESCRIPTION
**Pull request by HT154**
[YAML (1.2) explicitly allows _any_ value as a mapping key](https://yaml.org/spec/1.2.2/#3211-nodes), just like Pkl! This PR allows all of Pkl's primitive scalars (those that can already be natively rendered in YAML: Int, Float, Boolean, Null) to be rendered as mapping keys by `YamlRenderer`.

This PR does not attempt to allow non-scalar YAML mapping keys (see Example 2.11 at https://yaml.org/spec/1.2.2/#22-structures). This doesn't appear to be a commonly used YAML feature—I've never seen it in the wild—but may be interesting for Pkl to support. If this is desired, it could be taken on as follow-up work, but it might require significant modifications to `YamlRendererNodes.YamlRenderer`.

Resolves #878

### CODE REVIEW

File: pkl-core/src/main/java/org/pkl/core/stdlib/base/YamlRendererNodes.java [hunk 1]
```diff
@@ -278,8 +278,24 @@ protected void visitEntryKey(Object key, boolean isFirst) {
...
-        emitter.emit(string, currIndent, true);
+      if (key instanceof String stringKey) {
+        emitter.emit(stringKey, currIndent, true);
+        builder.append(':');
+        return;
+      } else if (key instanceof Long longKey) {
+        emitter.emit(longKey);
+        builder.append(':');
+        return;
+      } else if (key instanceof Double doubleKey) {
```
Comment (StefMa) [inline pkl-core/src/main/java/org/pkl/core/stdlib/base/YamlRendererNodes.java:289]: I am not sure with that, but what about Int(eger)? And why not just use Number instead?

**Review by StefMa — COMMENTED** [review]
Just one comment 🤓
On mobile you can't just comment on PRs, it is always a review 😡

File: pkl-core/src/main/java/org/pkl/core/stdlib/base/YamlRendererNodes.java (hunk 1 above)
Comment (HT154) [reply pkl-core/src/main/java/org/pkl/core/stdlib/base/YamlRendererNodes.java:289]: Pkl's `Int` types are all represented by Java `long` internally (likewise, Pkl `Float` is always Java `double`). In this case, `emitter` has two method overloads `emit(long)` and `emit(double)` so having a single case for `Number` doesn't work here.
