### PR TITLE
Do not throw if output dir is symlink

### LINKED ISSUE #621: Multiple file output does not work with symlinks
Using a regular output directory:

```shell
$ pkl eval -m output birds.pkl
output/birds/pigeon.json
output/birds/parrot.yaml
$ pkl eval -m output birds.pkl
output/birds/pigeon.json
output/birds/parrot.yaml
```

`birds.pkl` has the same content as [the example in the documentation](https://pkl-lang.org/main/current/language-reference/index.html#multiple-file-output).

Using a symlink:

```
$ DIR=$(mktemp -d)
$ pkl eval -m $DIR birds.pkl
../../../../../var/folders/p2/m6p8_spd68j2jbdnzwxxrvgr0000gn/T/tmp.ZMUU0W8BMv/birds/pigeon.json
../../../../../var/folders/p2/m6p8_spd68j2jbdnzwxxrvgr0000gn/T/tmp.ZMUU0W8BMv/birds/parrot.yaml
$ pkl eval -m $DIR birds.pkl
Output file conflict: `output.files` entry `"birds/pigeon.json"` in module `file:///[redacted]/birds.pkl` resolves to file path `/private/var/folders/p2/m6p8_spd68j2jbdnzwxxrvgr0000gn/T/tmp.ZMUU0W8BMv/birds/pigeon.json`, which is outside output directory `/var/folders/p2/m6p8_spd68j2jbdnzwxxrvgr0000gn/T/tmp.ZMUU0W8BMv`.
```

macOS symlinks `/var` to `/private/var`.

The related code path is the following:

https://github.com/apple/pkl/blob/8e15556201625bc1d37bb47666dbe225c7d3ebd9/pkl-cli/src/main/kotlin/org/pkl/cli/CliEvaluator.kt#L221-L227

### PR DESCRIPTION
**Pull request by StefMa**
fixes #621

### CODE REVIEW

File: pkl-cli/src/test/kotlin/org/pkl/cli/CliFormatterTest.kt [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright © 2025 Apple Inc. and the Pkl project authors. All rights reserved.
+ * Copyright © 2025-2026 Apple Inc. and the Pkl project authors. All rights reserved.
```
Comment (bioball) [inline pkl-cli/src/test/kotlin/org/pkl/cli/CliFormatterTest.kt]:
```suggestion
 * Copyright © 2025 Apple Inc. and the Pkl project authors. All rights reserved.
```

**Review by bioball — APPROVED** [review]
LGTM, thanks!

File: pkl-cli/src/test/kotlin/org/pkl/cli/CliFormatterTest.kt [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright © 2025 Apple Inc. and the Pkl project authors. All rights reserved.
+ * Copyright © 2025Apple Inc. and the Pkl project authors. All rights reserved.
```
Comment (bioball) [inline pkl-cli/src/test/kotlin/org/pkl/cli/CliFormatterTest.kt]:
```suggestion
 * Copyright © 2025 Apple Inc. and the Pkl project authors. All rights reserved.
```
