### PR TITLE
Fix VmFunction toString

### LINKED ISSUE #1410: Incorrect Function.toString()
The default Java `toString()` is leaking through:

```pkl
local myFunc = () -> null

res = myFunc.toString()
```

Produces:

```
res = "org.pkl.core.runtime.VmFunction@3cab13d4"
```

### PR DESCRIPTION
**Pull request by bioball**
Fixes an issue where the underlying default Java toString() is leaking through

Closes #1410

### CODE REVIEW

File: pkl-core/src/main/java/org/pkl/core/runtime/VmValueRenderer.java [hunk 1]
```diff
@@ -34,8 +34,13 @@ public final class VmValueRenderer {
   private final String interiorNewline;
   private final String indent;
   private String currIndent = "";
+  private static final VmValueRenderer maxSingleLine =
+      new VmValueRenderer(Integer.MAX_VALUE, " ", "; ", "");
```
Comment (stackoverflow) [inline pkl-core/src/main/java/org/pkl/core/runtime/VmValueRenderer.java:38]: Why do you need this special case renderer?

Comment (bioball) [reply pkl-core/src/main/java/org/pkl/core/runtime/VmValueRenderer.java:38]: Optimization; a bunch of different nodes use this, so we can just have them share the same instance here.
