### PR TITLE
Fix Map formatting

### LINKED ISSUE #1307: Incorrect formatting following a line comment in `Map()` call
These are considered correctly formatted:

```pkl
foo =
  Map(
    1, 2,
    3, 4, // hi!
    5,
    6,
    7, 8,
  )

bar =
  Map(
    1, 2,
    3, 4,
    // hi!
    5,
    6,
    7, 8,
  )
```

The two arguments following the line comment should be on the same line

### PR DESCRIPTION
**Pull request by stackoverflow**
Fixes #1307

### CODE REVIEW

File: pkl-formatter/src/main/kotlin/org/pkl/formatter/Builder.kt [hunk 1]
```diff
@@ -229,9 +229,14 @@ internal class Builder(sourceText: String, private val grammarVersion: GrammarVe
     if (children.size == 1) return format(children[0])
     val firstNode = node.firstProperChild()!!
     return if (firstNode.text() == "Map") {
-      val nodes = mutableListOf<FormatNode>()
-      nodes += format(firstNode)
-      nodes += formatArgumentList(children[1], twoBy2 = true)
+      val nodes =
```
Comment (stackoverflow) [inline pkl-formatter/src/main/kotlin/org/pkl/formatter/Builder.kt:232]: This is a slightly related bugfix.

File: pkl-formatter/src/test/files/FormatterSnippetTests/input/map-function.pkl [hunk 2]
```diff
@@ -2,3 +2,18 @@
...
 
 incorrect = Map("This has", 1000000, "an incorrect number", 2000000, "of parameters", 30000000, "passed to Map")
+
+bar =
+  Map(
+    // leading
+    1,
+    2,
+    3,
+    4, // trailing
```
Comment (HT154) [inline pkl-formatter/src/test/files/FormatterSnippetTests/input/map-function.pkl:13]: Can we also test that line comments between pairs work as expected?
```suggestion
  Map(
    // leading
    1,
    2,
    // between
    3,
    4, // trailing
```

Comment (stackoverflow) [reply pkl-formatter/src/test/files/FormatterSnippetTests/input/map-function.pkl:13]: Added.
